<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="robots" content="index,nofollow"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<link href="/assets/css/th.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<link rel="icon" href="/favicon.ico" type="image/x-icon"/>
<link rel="Shortcut Icon" href="/favicon.ico"/>
<?php echo $this->headScript() ?>
<script type="text/javascript" src="/assets/js/clearBox.js"></script>
<script type="text/javascript" src="/assets/js/bookmark-us.js"></script> 
<meta name="google-site-verification" content="okOMkac9K7fLWq5k42GpdRhH8Mw84YNwTAb-aEu84kQ" />
</head>

<body>

<div id="wrapper">
	<div id="contentHolder">
		<div id="topBar">
			<a href="/"><img id="logo" src="/assets/images/th-logo.jpg" width="333" height="72" alt="Top Health Spot" /></a>
			<div id="Bookmark">
				<div style="margin-bottom:0.3em;margin-left:0.3em">Save &nbsp; RSS</div>
					<div>
						<a href="javascript:bookmarksite('TopHealthSpot - Health Product Coupons, Discounts, and More..', window.location.href)"><img src="/assets/images/favorite-icon.png" width="32" height="32" alt="Bookmark" style="border:0;" /></a>
						<a href="/feed/rss.xml" target="_blank"><img src="/assets/images/feed-icon.png" width="32" height="32" alt="RSS Feed" style="border:0;" /></a>
					</div>
				</div>
				<div id="socialSites">
					<div style="margin-bottom:0.3em;margin-left:0.2em">Follow us on social sites</div>
					<div>
						<a href="http://twitter.com/tophealthspot" title="Twitter" target="_blank"><img src="/assets/images/twitter-icon.png" width="32" height="32" alt="Twitter" style="border:0;" /></a>
						<a href="http://facebook.com/home.php?#/profile.php/?ref=profile&id=1398900200" title="Facebook" target="_blank"><img src="/assets/images/facebook-icon.png" width="32" height="32" alt="FaceBook" style="border:0;" /></a>
						<a href="http://myspace.com/tophealthspot" title="MySpace" target="_blank"><img src="/assets/images/myspace-icon.png" width="32" height="32" alt="MySpace" style="border:0;" />
						<a href="http://tophealthspot.tumblr.com/" title="Tumblr" target="_blank"><img src="/assets/images/tumblr-icon.png" width="32" height="32" alt="Tumblr" style="border:0;" />
					</div>
				</div>
				<div id="siteSearch">
					<a href="/"><span style="margin-left:0.3em">Home</span></a> | 
					<a href="/content/2/about-us/"><span>About Us</span></a> | 
					<a href="/content/4/top-health-faqs/"><span>FAQS</span></a> | 
					<a href="/content/contact-us/"><span>Contact Us</span></a>
					<form id="site-search" action="/index/search/search/" method="get" >
					<input type="text" name="searchBox" id="searchBox" value="Search..." />
					<input type="submit" id="submit" name="submit" value="Search" />
					</form>
				</div>
			</div>
			<div id="navMenu">
				<ul><li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 105 ? "on" : "off"); ?>"><a href="/store/105/TriLASTIN---Stretch-Mark-Cream/category/3" title="TriLastin">TRILASTIN</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 16  ? "on" : "off"); ?>"><a href="/store/16/Vitamin%20Shoppe/category/10" title="Vitamins and Coupons">VITAMINS &amp; SUPPLEMENTS</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 4   ? "on" : "off"); ?>"><a href="/store/4/Medifast%20Coupons/category/11" title="Diet and Weight Management">DIET &amp; WEIGHT MANAGEMENT</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 13  ? "on" : "off"); ?>"><a href="/store/13/Free%20Diet%20To%20Go%20Coupons/category/1" title="Online Diet Plans">ONLINE DIET PLANS</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 25  ? "on" : "off"); ?>"><a href="/store/25/Revitol%20Stretch%20Mark/category/12" title="Skin Care Products">SKIN CARE PRODUCTS</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 60  ? "on" : "off"); ?>"><a href="/store/121/Beautorium---Organic-Skin-Care/category/3" title="Beauty Products">BEAUTY PRODUCTS</a></li>
				</ul>
				<ul><li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 8   ? "on" : "off"); ?>"><a href="/store/8/Gaiam%20Store%20Online/category/2" title="Health and Fitness">HEALTH &amp; FITNESS</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 2   ? "on" : "off"); ?>"><a href="/store/2/Bowflex/category/5" title="Fitness Equipment">FITNESS EQUIPMENT</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 29  ? "on" : "off"); ?>"><a href="/store/29/The-Grooming-Lounge/category/6" title="Mens Products">MENS PRODUCTS</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 93  ? "on" : "off"); ?>"><a href="/store/112/Allegro%20Medical%20-%20Medical%20Supplies/category/13" title="Mobility Aids">MOBILITY AIDS</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 122 ? "on" : "off"); ?>"><a href="/store/122/American%20Diabetes%20Wholesale/category/7" title="Diabetic Supplies">DIABETIC SUPPLIES</a></li>
					<li class="nav_<?php echo (isset($this->store) && $this->store->getStoreID() == 154 ? "on" : "off"); ?>"><a href="/store/154/ShopInPrivate.com/category/9" title="Sexual Well-Being">SEXUAL WELL-BEING</a></li>
				</ul>
			</div>
			<div id="titleHolder"><h1>
			<?php
			if (isset($this->category)) echo "TopHealthSpot, ".$this->category->getName();
			else if (isset($this->subCategory)) echo "TopHealthSpot, ".$this->subCategory->getName();
			else if (isset($this->store)) echo "TopHealthSpot, ".$this->store->getName();
			else echo $this->h1_1;			
			?>			
			</h1></div>
		</div>
		
	<div id="mainContent">
		
		<div id="leftColumn">
		<?php if ($this->StoreDropDown) { ?>
			<div id="headerLeftColumn"><h2 class="headerCouponsByStore"><?php echo $this->h3_1; ?></h2></div>
			<div id="leftColumnTop"></div>
			<div id="leftColumnBody">
			<?php //This statement paints a drop down of all stores			
			if ($this->StoreDropDown) echo $this->StoreDropDown;
				//This foreach returns all stores with coupons
			if (is_array($this->layoutStores)) {
			?>
				<ul>
			<?php foreach ($this->layoutStores as $store) { ?>
					<li class="storeLinks"><a href="/store/<?php echo $store['storeID']; ?>/<?php echo $this->titleUrl($store['storeName']) ; ?>/"><?php echo htmlspecialchars($store['storeName'], null, null, false); ?></a></li>
			<?php } ?>
							<li><a style="font-size:12px;font-weight:bold;margin:0 5px 0 28px;color:#2A6825;" href="/store">&lt;&lt; view all stores &gt;&gt;</a></li>
							</ul>
			<?php } ?>
			</div>
			<div id="leftColumnBottom"></div>
		<?php } ?>
			<div id="headerLeftColumn"><h2 class="headerCouponCategories"><?php echo $this->h3_2; ?></h2></div>
			<div id="leftColumnTop"></div>
			<div id="leftColumnBody">
			
							<ul>
							<?php //This foreach returns the categories
							foreach( $this->layoutCategories as $categoryID => $category ){ ?>
								 <li class="catTitles"><a href="/category/<?php echo $categoryID .'/' . $this->titleUrl($category['name']) ; ?>/"><?php echo htmlspecialchars($category['name'], null, null, false); ?></a></li>	
							<?php // This foreach returns all the subcategories
								if (isset($category['subCategories'])) { $numSubCategories = count( $category['subCategories']); $i=0; 
								foreach ( $category['subCategories'] as $subCategoryID => $subCategory ) { ?>
<!--
								<li <?php if( $i == $numSubCategories - 1){ echo 'class="endLink"'; } ?>>
								<ul>
								<li class="subCatTitles"><a href="/sub-category/<?php echo $subCategoryID; ?>/<?php echo $this->titleUrl($subCategory['name']); ?>/" ><?php echo htmlspecialchars($subCategory['name'], null, null, false); ?></a></li>	
								</ul>
								</li>
//-->								
									<?php 
									if (isset($subCategory['coupons'])) { $numCoupons = count( $subCategory['coupons']); $j=0; 
									foreach ( $subCategory['coupons'] as $storeID => $storeName ) { ?>
									
									<li <?php if( $j == $numCoupons - 1){ echo 'class="endLink"'; } ?>>
										<ul>
											<li class="storeLinks"><a href="/store/<?php echo $storeID; ?>/<?php echo $this->titleUrl($storeName); ?>/"><?php echo htmlspecialchars($storeName, null, null, false); ?></a></li>	
										</ul>
									</li>
	    							<?php $j++; } 	
    							 $i++; }?> 
    							 <?php }}} ?>
    						<?php if (isset($subCategory['coupons'])) { ?>
    						<a style="font-size: 12px; font-weight: bold; margin: 0pt 5px 0pt 28px; color: rgb(42, 104, 37);" href="/">&lt;&lt; back to home &gt;&gt;</a>
    						<?php } ?>
			
			</div>
			<div id="leftColumnBottom"></div>		
		</div>		

		<?php echo $this->layout()->content; ?>

	</div>
	<div id="mainContent">
		<div id="footer">
				<div id="footerTop"></div>
				<div id="footerLinks">
				<ul><li><a href="/store/105/TriLASTIN---Stretch-Mark-Cream/category/3" title="TriLastin"><span>TRILASTIN</span></a></li>
					<li><a href="/store/16/Vitamin%20Shoppe/category/10" title="Vitamins & Supplements"><span>VITAMINS &amp; SUPPLEMENTS</span></a></li>
					<li><a href="/store/4/Medifast%20Coupons/category/11" title="Diet & Weight Management"><span>DIET &amp; WEIGHT MANAGEMENT</span></a></li>
					<li><a href="/store/13/Free%20Diet%20To%20Go%20Coupons/category/1" title="Online Diet Plans"><span>ONLINE DIET PLANS</span></a></li>
					<li><a href="/store/25/Revitol%20Stretch%20Mark/category/12" title="Skin Care Products"><span>SKIN CARE PRODUCTS</span></a></li>
					<li><a href="/store/121/Beautorium---Organic-Skin-Care/category/3" title="Beauty Products"><span>BEAUTY PRODUCTS</span></a></li>
					<li><a href="/store/8/Gaiam%20Store%20Online/category/2" title="Health & Fitness"><span>HEALTH &amp; FITNESS</span></a></li>
					<li><a href="/store/2/Bowflex/category/5" title="Fitness Equipment"><span>FITNESS EQUIPMENT</span></a></li>
					<li><a href="/store/29/The-Grooming-Lounge/category/6" title="Mens Products"><span>MENS PRODUCTS</span></a></li>
					<li><a href="/store/112/Allegro%20Medical%20-%20Medical%20Supplies/category/13" title="Mobility Aids"><span>MOBILITY AIDS</span></a></li>
					<li><a href="/store/122/American%20Diabetes%20Wholesale/category/7" title="Diabetic Supplies"><span>DIABETIC SUPPLIES</span></a></li>
					<li class="lastLink"><a href="/store/154/ShopInPrivate.com/category/9" title="Sexual Well-Being"><span>SEXUAL WELL-BEING</span></a></li>
					<li><a href="/content/5/Privacy-Policy" title="Privacy Policy"><span>PRIVACY POLICY</span></a></li>
					<li><a href="/content/6/top-health-terms" title="Terms & Conditions"><span>TERMS &amp; CONDITIONS</span></a></li>
				</ul>
				</div>
				<div id="footerBody">
					<p>
					The information provided on this site is for informational purposes only and is not intended as a substitute for advice from your physician or other health care professional or any information contained on or in any product label or packaging. 
					You should not use the information on this site for diagnosis or treatment of any health problem or for prescription of any medication or other treatment. 
					You should consult with a healthcare professional before starting any diet, exercise or supplementation program, before taking any medication, or if you have or suspect you might have a health problem. 
					</p>
					<p>All of the deals, coupons, and promotions on this site are subject to change without notice. Tophealthspotcom does not at any time guarantee the accuracy of links, coupons, or deals that are found anywhere on this site.</p>
					<p>Tophealthspot.com is an online shopping portal used to save you money on the Internet we are not responsible for any products ordered from our affiliate merchants.Before participating in or using any promotional code, discount offer, merchant coupons and deals offered through Tophealthspot.com at any time you must read the fine print associated with each offer as it is written in its original form from the affiliate merchant.</p>
					<p>Make sure that the correct coupon code or current merchant offer has been applied to your shopping cart before accepting or confirming a purchase. This step will confirm that the discount or merchant coupon has been applie= d to your order at point of sale.</p>
					<p>All design, content text, original articles and images used within the entire pages of Tophealthspot.com including our blog Healthblogshop.com are &copy; Copyright <?php $startYear = "2009"; if ($startYear == date('Y')) {echo $startYear; } else { echo $startYear . '-' . date('Y') . ','; } ?> Tophealthspot.com, All Rights Reserved.</p>
					<div id="footerIntLinks">
						<ul id="block-a">
							<li><a href="/content/16/TriLastin%20Coupon" title="TriLastin Coupon">TriLastin Coupon</a></li>
							<li><a href="/content/12/Cellulite%20Cream" title="Cellulite Cream">Cellulite Cream</a></li>
						</ul>
						<ul id="block-b">
							<li><a href="/content/19/Revitol%20Scar%20Cream" title="Revitol Scar Cream">Revitol Scar Cream</a></li>
							<li><a href="/store/60/Beauty.com/category/3" title="Beauty.com">Beauty.com</a></li>
						</ul>
						<ul id="block-c">
							<li><a href="/store/8/Gaiam%20Store%20Online/category/2" title="Gaiam">Gaiam</a></li>
							<li><a href="/store/4/Medifast%20Coupons/category/11" title="Medifast">Medifast</a></li>
						</ul>
						<ul id="block-d">
							<li><a href="/store/16/Vitamin%20Shoppe/category/10" title="Vitamin Shoppe">Vitamin Shoppe</a></li>
							<li><a href="/store/139/Horizon%20Fitness/category/5" title="Horizon Fitness">Horizon Fitness</a></li>
						</ul>
						<ul id="block-e">
							<li><a href="/store/58/Drugstore.com%20Discounts/category/10" title="Drugstore.com">Drugstore.com</a></li>
							<li><a href="/store/112/Allegro%20Medical%20-%20Medical%20Supplies/category/13" title="Mobility Scooters">Mobility Scooters</a></li>
						</ul>
					</div>	
				</div>
			<div id="footerBottom"></div>
			<div id="footerCopy">
				&copy; Copyright <?php echo date('Y'); ?> Top Health Spot - All Rights Reserved - Owned By GS Enterprises LTD.
			</div>
		</div>
	</div>
		
</div>
</div>

</body>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-7890014-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</html>	
