				<div id="sliderNav">
					<ul id="slideNav">
						<li id="link7"><a class="toc" href="#"><span>1</span></a></li>
						<li id="link8"><a class="toc"  href="#"><span>2</span></a></li>
						<li id="link9"><a class="toc"  href="#"><span>3</span></a></li>
						<li id="link10"><a class="toc"  href="#"><span>4</span></a></li>
						<li id="link11"><a class="toc"  href="#"><span>5</span></a></li>
						<li id="link12"><a class="toc"  href="#"><span>6</span></a></li>
					</ul>
				</div>