      	<div class="box">
      	<div style="float:right;width:200px;margin-top:5em;padding-right:20px;">
      	<div style="font-weight:bold;font-size:14px;">Valid Dimensions</div><br />
      	<span style="font-weight:bold;">small square</span><br />
      	<div>100 width x 100 height</div>
      	<div>(same as 125x125)</div><br />
      	<span style="font-weight:bold;">large square</span><br />
      	<div>210 width x 210 height</div>
      	<div>(same as 250x250)</div><br />
      	<span style="font-weight:bold;">horizontal rectangle</span><br />
      	<div>210 width x 105 height</div>
      	<div>(same as 250x125)</div><br />
      	<span style="font-weight:bold;">vertical rectangle</span><br />
      	<div>100 width x 480 height</div>
      	<div>(same as 125x600)</div>
      	<hr noshade /><br />
      	<div style="font-weight:bold;font-size:14px;">Input Legend</div><br />     	
		<span style="font-weight:bold;">Image URL</span><br />
      	<div>The URL where the image is pulled from. Embeds the image in the page.</div><br />
		<span style="font-weight:bold;">Destination</span><br />
      	<div>The URL that the image links to. Goes to this site when the image is clicked on.</div>
      	</div>
      	
      		<h4 class="white">Edit Ad Banner</h4>
        <div class="box-container">
						<?php echo $this->form; ?>
      				<span class="clearFix">&nbsp;</span>
        </div><!-- end of div.box-container -->
      	</div><!-- end of div.box -->

