
		<div id="rightColumn">
			<div id="headerRightColumn"><h2 class="headerSpecialDeals">Special Deals</h2></div>
			<div id="rightColumnTop"></div>
			<div id="rightColumnBody">

							<?php
							if ($this->layoutSpecials)
							{
								$j = 0;
								foreach ($this->layoutSpecials as $special)
								{
									++$j; $i = 0;
									echo "<div class='".($j == 1 ? "firstSpecial" : "nextSpecial")."'>$special[name]</div>";
									foreach ($special['coupons'] as $coupon)
										echo "<div class='specialstore'>".++$i.". $coupon[storeName]</div><div class='specialcoupon'><a href='/coupon/$coupon[couponID]/".$this->titleUrl($coupon['storeName'])."/".$this->titleUrl($coupon['description'])."/use/1' target='_new'>$coupon[description]</a></div>";
								}
							}
							?>
			
			</div>
			<div id="rightColumnBottom"></div>	
			<div id="headerRightColumn"><h2 class="headerLatestBlogs">Latest Blog Entries</h2></div>
			<div id="rightColumnTop"></div>
			<div id="rightColumnBody">
				<div id="blogFeed">
					<ul>
					<?php foreach ( $this->feed as $item ){?>
						<li><a href="<?php echo $item->getLink(); ?>" target="_new"><?php echo $item->getTitle(); ?></a></li>
					<?php }?>
					</ul>
				</div>
			</div>
			<div id="rightColumnBottom"></div>
			
			<div style="margin-left: -0.28em">
			<?php foreach( $this->adBanners as $adBanner) { ?>
    	 		<div class="adBanner"><a href="<?php echo $adBanner['href']; ?>" target="_new"><img src="<?php echo $adBanner['image']; ?>" width="<?php echo $adBanner['width']; ?>" height="<?php echo $adBanner['height']; ?>" style="border:0;" alt="<?php echo $adBanner['alt']; ?>" /></a></div>
    	 	<?php } ?>
    	 	</div>

		</div>

		<div id ="centerColumn">

		<?php if(isset($this->indexHeader)) echo $this->indexHeader; ?>

			<div id="centerColumnTop"></div>
			<div id="centerColumnBody">
			
				<h2>Available Health Coupons</h2>
				<br class="featuredBR" />

				<div style="margin-right: 0.25em">

	<?php foreach( $this->searchPaginator as $coupon) {  ?>
			<ul class="couponBox">
			
				<li class="couponLogo">
					<a href="/store/<?php echo $coupon['storeID']; ?>/<?php echo $this->titleUrl($coupon['storeName']); ?>/"><img src="/assets/images/store-logos/<?php echo $coupon['storeID']; ?>.jpg" width="100" alt="<?php echo $coupon['storeName']; ?>" style="border: 1px solid #E48022;" /></a>
				</li>
	
				<li class="couponData">
			
					<div class="couponTitle"><a href="/coupon/<?php echo $coupon['couponID']; ?>/<?php echo $this->titleUrl($coupon['storeName']); ?>/<?php echo $this->titleUrl($coupon['description']); ?>/use/1" target="_new"><?php echo $coupon['description']; ?></a></div>
					<div class="couponDescription"><?php echo $coupon['secondaryDescription']; ?></div>

				</li>

				<li class="couponCodeExpiration">
					Expires: <?php echo $coupon['expirationDate']; ?><br />
					Code: <?php echo (preg_match('/needed/i', $coupon['couponCode']) ? '----------------' : $coupon['couponCode']); ?>
				</li>
						
				<li class="couponButtons">
					<a href="/coupon/<?php echo $coupon['couponID']; ?>/<?php echo $this->titleUrl($coupon['storeName']); ?>/<?php echo $this->titleUrl($coupon['description']); ?>/use/1" target="_new"><img src="/assets/images/use_coupon.gif" width="47" alt="Use This Coupon" border="0" /></a>
				</li>
						
			</ul>	

				<?php } ?>
					
			</div>
			
			</div>
			<div id="centerColumnBottom"></div>
		</div>
