		
		<div id="rightColumn">
			<div id="headerRightColumn"><h2 class="headerLatestBlogs"><?php echo $this->h3_4; ?></h2></div>
			<div id="rightColumnBottom"></div>	
			<div id="headerRightColumn"><h2 class="headerLatestBlogs"><?php echo $this->h3_4; ?></h2></div>
			<div id="blog_graphic">
			<a href="/blog" title="Health & Beauty Blog" target="_blank"><img src="/assets/images/blog_graphic.jpg" alt="Health & Beauty Blog" style="border: 0;margin: 5px;" /></a>
			<hr noshade />
			</div>
		</div>
		
<div id ="centerColumn">

<div id="centerColumnTop"></div>
<div id="centerColumnBody">

<h2>Contact Us</h2>
<br class="featuredBR" />

<?php if ($this->success) { ?>
<div id="formSuccess">&nbsp;&nbsp; <?php echo $this->success; ?></div>
<?php } ?>

<div id="contactUs">
<?php echo $this->contactUsForm; ?>
</div>

</div>
<div id="centerColumnBottom"></div>

</div>