<?php $this->headScript()->appendFile('/assets/js/select-chain.js', 'text/javascript'); ?>
<?php $this->headScript()->captureStart()  ?>
 $(document).ready(function() {
	$('#categoryID').selectChain({
	    target: $('#subCategoryID'),
	    url: '/admin/sub-category/get-sub-categories-by-category',
	    type: 'post',
	    data: "ajax=true"
	});
 });
<?php $this->headScript()->captureEnd() ?>
      	<div class="box">      
      		<h4 class="white">Edit Page</h4>
        <div class="box-container">
						<?php echo $this->form; ?>
      				<span class="clearFix">&nbsp;</span>
        </div><!-- end of div.box-container -->
      	</div><!-- end of div.box -->

