      	<div class="box">
      		<h4 class="white">Sub Categories</h4>
        <div class="box-container">     		
      		<table class="table-long">
      			<thead>
      				<tr>
      					<td width="5%"></td>
      					<td width="5%">ID</td>
      					<td width="20%">Name</td>
      					<td width="20%">Parent Category</td>      					
      					<td width="30%">Title</td>
      					<td width="15%"></td>
      				</tr>
      			</thead>
      			<tfoot>
      				<tr>
      					<td class="col-chk"></td>
      					<td colspan="5"><div class="align-right">
      					<a href="/admin/sub-category/add/" class="button"><span>Add Sub Category</span></a></div></td>
      				</tr>
      			</tfoot>
      			<tbody>
		<?php 
		foreach( $this->paginator AS $content ){ ?>      			
      				<tr class="<?php echo $this->cycle(array("","odd"))->next()?>">
      					<td class="col-chk"><input type="checkbox" /></td>
      					<td class="col-first"><?php echo $content->subCategoryID; ?></td>
      					<td class="col-second"><?php echo $content->name; ?></td>
      					<td class="col-third"><?php echo $content->categoryName; ?></td>      					
      					<td class="col-fourth"><?php echo $content->pageTitle; ?></td>      					
      					<td class="row-nav"><a href="/admin/sub-category/edit/id/<?php echo $content->subCategoryID; ?>" class="table-edit-link">Edit</a> <span class="hidden"> | </span> <a href="/admin/sub-category/delete/id/<?php echo $content->subCategoryID; ?>" class="table-delete-link">Delete</a></td>
      				</tr>
      			</tbody>
		<?php  } ?>
      			
      		</table>  	
      	</div><!-- end of div.box-container -->
      	</div> <!-- end of div.box -->
      	      	      	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
      	